name: Build project

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build project
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
          java-package: jdk+fx

      - name: Build
        run: gradle build
