name: Build project

on: push

jobs:
  build:
    name: Build project
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set RELEASE_VERSION env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/v*/}" >> $GITHUB_ENV

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
          java-package: jdk+fx

      - name: Build
        run: gradle build
