name: Upload assets to release

on:
  create:
    tags:
      - v*

jobs:
  release:
    name: Upload assets to release
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set appVersion
        uses: bhowell2/github-substring-action@v1
        id: appVersion
        with:
          value: ${{github.ref}}
          index_of_str: "refs/tags/v"

      - run: echo "App Version = ${{steps.appVersion.outputs.substring}}"

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
          java-package: jdk+fx

      - name: Package
        run: gradle jpackage

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: build/jpackage/TournamentTool-${{steps.appVersion.outputs.substring}}.msi
          overwrite: true
