name: Upload assets to release

on:
  create:
    tags:
      - v*

jobs:
  release:
    name: Upload assets to release
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set RELEASE_VERSION env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/v*/}" >> $GITHUB_ENV

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
          java-package: jdk+fx

      - name: Package
        run: gradle jpackage

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: target/jpackage/TournamentTool-${{env.RELEASE_VERSION}}.msi
          overwrite: true
