name: Upload assets to release

on:
  create:
    tags:
      - v*

jobs:
  release:
    name: Upload assets to release
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: echo "GITHUB_CONTEXT=${GITHUB_CONTEXT}"
      - run: echo "GITHUB_REF=${GITHUB_REF}"


      - name: Set RELEASE_VERSION env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - run: echo "RELEASE_VERSION = ${{env.RELEASE_VERSION}}"

      - name: Set APP_VERSION env
        run: echo "APP_VERSION=$(echo ${env.RELEASE_VERSION:1})" >> $GITHUB_ENV

      - run: echo "APP_VERSION = ${{env.APP_VERSION}}"


      - name: Print GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "The event name is ${{ github.event_name }}"
          echo "$GITHUB_CONTEXT"

      - run: echo "::debug::${GITHUB_CONTEXT}"
      - run: echo "::debug::${GITHUB_REF}"
      - run: echo "::debug::${GITHUB_REF#refs/*/}"
      - run: echo "::debug::${env.RELEASE_VERSION}"
      - run: echo "::debug::${env.APP_VERSION}"


      - name: Set gitTag (with set-output)
        id: gitTag
        run: echo ::set-output name=gitTag::${GITHUB_REF#refs/*/}

      - run: echo "tag={{steps.gitTag.outputs.gitTag}}"

      - name: Set appVersion env (with set-output)
        uses: bhowell2/github-substring-action@v1
        id: appVersion
        with:
          value: ${GITHUB_REF#refs/*/}
          index_of_str: "v"

      - run: echo "appVersion={{steps.appVersion.outputs.substring}}"



      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
          java-package: jdk+fx

      - name: Package
        run: gradle jpackage

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: target/jpackage/TournamentTool-${{env.APP_VERSION}}.msi
          overwrite: true
