name: Upload assets to release

on:
  create:
    tags:
      - v*

jobs:
  release:
    name: Upload assets to release
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: echo "github.ref is ${{ github.ref }}"

      - name: Print GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "The event name is ${{ github.event_name }}"
          echo "github.ref is ${{ github.ref }}"
          echo "GITHUB_CONTEXT=$GITHUB_CONTEXT"

      - name: Set appVersion
        uses: bhowell2/github-substring-action@v1
        id: appVersion
        with:
          value: ${{github.ref}}
          index_of_str: "refs/tags/v"

      - run: echo "appVersion=${{steps.appVersion.outputs.substring}}"



      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
          java-package: jdk+fx

      - name: Package
        run: gradle jpackage

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: target/jpackage/TournamentTool-${{env.APP_VERSION}}.msi
          overwrite: true
